# Generated by Django 5.0.6 on 2024-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=50)),
                ("session_id", models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
